import {
  DERIVATIVES_TRADING_USDS_FUTURES_WS_STREAMS_TESTNET_URL,
  DERIVATIVES_TRADING_USDS_FUTURES_WS_STREAMS_PROD_URL
} from '@binance/derivatives-trading-usds-futures';

console.log('TESTNET_WS:', DERIVATIVES_TRADING_USDS_FUTURES_WS_STREAMS_TESTNET_URL);
console.log('PROD_WS:', DERIVATIVES_TRADING_USDS_FUTURES_WS_STREAMS_PROD_URL);
