export const CONFIG_LIMITS = {
  WATCHLIST_MIN: 1,
  WATCHLIST_MAX: 200,
  WATCHLIST_DEFAULT: 25,

  SL_DISTANCE_MIN: 0.1,
  SL_DISTANCE_MAX: 10.0,
  SL_DISTANCE_DEFAULT: 0.8,

  RISK_PER_TRADE_MIN: 0.01,
  RISK_PER_TRADE_MAX: 100.0,
  RISK_PER_TRADE_DEFAULT: 1.0,

  MAX_TOTAL_RISK_MIN: 0.1,
  MAX_TOTAL_RISK_MAX: 100.0,
  MAX_TOTAL_RISK_DEFAULT: 5.0,

  HOT_LOOP_MIN: 500,
  HOT_LOOP_DEFAULT: 5000,
  MAIN_LOOP_MIN: 1000,
  MAIN_LOOP_DEFAULT: 15000,

  MAX_VARIANTS: 10,
  MAX_SINGLE_SYMBOL_MONITORS: 100,
  MAX_TRADING_WINDOWS: 10,
  MAX_SIGNALS: 20,
};

export const ENGINE_CONSTANTS = {
  BINANCE_WS_BASE: process.env.BINANCE_WS_BASE || 'wss://fstream.binance.com/market',
  BINANCE_REST_BASE: process.env.BINANCE_REST_BASE || 'https://fapi.binance.com',
  KLINE_STREAM_CHUNK_SIZE: 20,
  WATCHLIST_REFRESH_INTERVAL_MS: 120000,
  TICKER_BOOTSTRAP_TIMEOUT_MS: 5000,
  BACKFILL_MAX_JITTER_MS: 2000,
  USER_DATA_KEEPALIVE_MS: 30 * 60 * 1000,
  BINANCE_RATE_LIMIT_DEFAULT: 1200,
  SCANNER_MAX_RESULTS: 15,
  SCANNER_UI_RESULTS: 5,
  HISTORY_UI_LIMIT: 50,
  ANALYTICS_UI_POINTS: 20,
  SPARKLINE_HISTORY_LEN: 20,
};
