import { SessionConfig } from '../../models/SessionConfig';

export interface TradeSerializationDto {
  id: string;
  symbol: string;
  strategy_label: string;
  current_price: number;
  sl_price: number;
  tp_price: number | null;
  pnl: number;
  pnl_pct: number;
  realized_fee: number;
  funding_fee?: number;
  rr: number;
  max_rr: number;
  max_rr_achieved?: number;
  direction: 'LONG' | 'SHORT';
  entry_price: number;
  qty: number;
  paper_mode?: boolean;
  trading_mode?: 'paper' | 'testnet' | 'live';
  exit_signals_status?: Record<string, any>;
  sl_adjustments?: any[];
  live_rr_sequence?: number[];
  exit_rr_sequence?: number[];
  tp_mode?: 'fixed' | 'exp_rr_seq';
  tp_ratio?: number;
  exit_signal_logic?: 'any' | 'all';
  strategy_config?: Partial<SessionConfig>;
  entry_daily_change_pct?: number;
  initial_risk_usdt?: number;
  risk_usdt?: number;
  close_attempts?: number;
  close_blocked?: boolean;
  est_pnl_to_realize?: number;
  est_pnl_source?: string;
  exit_rr?: number;
  min_rr_achieved?: number;
  rr_sequence_index?: number;
  _delta?: boolean;
  _thin?: boolean;
  _sl_len?: number;
  _sig_json?: string;
}

export interface TickTradeDto {
  id: string;
  symbol: string;
  strategy_label: string;
  current_price: number;
  sl_price: number;
  tp_price: number | null;
  pnl: number;
  pnl_pct?: number;
  realized_fee: number;
  funding_fee?: number;
  rr: number;
  max_rr: number;
  max_rr_achieved?: number;
  direction: 'LONG' | 'SHORT';
  entry_price: number;
  qty: number;
  entry_daily_change_pct?: number;
  close_attempts?: number;
  close_blocked?: boolean;
  initial_risk_usdt?: number;
  risk_usdt?: number;
  est_pnl_to_realize?: number;
  est_pnl_source?: string;
  exit_rr?: number;
  min_rr_achieved?: number;
  rr_sequence_index?: number;
  _thin: boolean;
  _sl_len: number;
  _sig_json: string;
  live_rr_sequence?: number[];
  exit_rr_sequence?: number[];
}
