import { Injectable, Logger } from '@nestjs/common';
import { TradeEntity } from '../models/entities/Trade.entity';
import { roundTo } from '../lib/math';

export interface PeriodicStat {
  pnl: number;
  pnlPct: number;
}

export interface HistoryPoint {
  label: string;
  pnl: number;
  pnlPct: number;
}

export interface AnalyticsResult {
  cumulativePnL: { ts: string; pnl: number }[];
  maxDrawdown: number;
  maxDrawdownPct: number;
  timeOfDay: {
    hour: number;
    pnl: number;
    wins: number;
    total: number;
    winRate: number;
  }[];
  totalTrades: number;
  overallWinRate: number;
  overallPnlPct: number;
  avgWin: number;
  avgLoss: number;
  avgWinPct: number;
  avgLossPct: number;
  expectancyPct: number;
  avgWinLossRatio: number;
  profitFactor: number;
  sharpeRatio: number;
  sortinoRatio: number;
  periodic: {
    daily: PeriodicStat;
    weekly: PeriodicStat;
    monthly: PeriodicStat;
  };
  periodicHistory: {
    daily: HistoryPoint[];
    weekly: HistoryPoint[];
  };
}

@Injectable()
export class AnalyticsService {
  private readonly logger = new Logger(AnalyticsService.name);

  /**
   * PERFORMANCE OPTIMIZATION: Single-pass O(N) processing using timestamp math.
   * Minimizes object creation in loop. Uses a deposit-immune ROI basis.
   *
   * Capital Neutrality Logic: ROI is calculated relative to (Initial Balance + PnL before trade).
   * Deposits/transfers shift the absolute balance but don't change the relative PnL generated by trades.
   */
  calculateAnalytics(trades: TradeEntity[], startingBalance: number = 10000, currentBalance?: number): AnalyticsResult {
    const sortedTrades = [...trades]
      .filter(t => t.status !== 'OPEN' && t.exit_ts && !t.is_reconciliation)
      .sort((a, b) => a.exit_ts!.getTime() - b.exit_ts!.getTime());

    const totalTrades = sortedTrades.length;
    let currentPnL = 0;
    let maxPnL = 0;
    let maxDD = 0;
    let maxDDPct = 0;
    let totalWins = 0;
    let totalLosses = 0;
    let grossProfit = 0;
    let grossLoss = 0;
    let grossProfitPct = 0;
    let grossLossPct = 0;
    let sumReturnPct = 0;
    let sumSquaredReturnPct = 0;
    let downsideSumSquaredReturnPct = 0;

    const totalNetPnL = sortedTrades.reduce((sum, t) => sum + Number(t.pnl || 0), 0);

    // Capital Neutrality: The 'Starting Balance' is the anchor.
    // If currentBalance is provided, it's used to derive the starting balance at the BEGINNING of history.
    const effectiveStartingBalance = (currentBalance && currentBalance > 0)
      ? Math.max(1, currentBalance - totalNetPnL)
      : startingBalance;

    let rollingBalance = effectiveStartingBalance;
    const cumulativePnL: { ts: string; pnl: number }[] = new Array(totalTrades);
    const todStats = Array.from({ length: 24 }, () => ({ pnl: 0, wins: 0, total: 0 }));

    const now = new Date();
    const startOfDayTs = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())).getTime();

    const dayOfWeek = now.getUTCDay();
    const diff = dayOfWeek === 0 ? 6 : dayOfWeek - 1;
    const startOfWeekTs = startOfDayTs - (diff * 86400000);

    const startOfMonthTs = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).getTime();

    let dailyPnL = 0;
    let weeklyPnL = 0;
    let monthlyPnL = 0;

    let dailyStartBal = rollingBalance;
    let weeklyStartBal = rollingBalance;
    let monthlyStartBal = rollingBalance;

    const dailyBuckets = new Map<number, { pnl: number, startBal: number }>();
    const weeklyBuckets = new Map<number, { pnl: number, startBal: number }>();

    for (let i = 0; i < totalTrades; i++) {
      const t = sortedTrades[i];
      const pnl = Number(t.pnl || 0);
      const exitTs = t.exit_ts!.getTime();

      const tradeStartBal = rollingBalance;
      const tradeReturnPct = tradeStartBal > 0 ? (pnl / tradeStartBal) * 100 : 0;

      // Update boundaries starting balance if this is the first trade of that period
      if (exitTs < startOfDayTs) dailyStartBal = rollingBalance + pnl;
      if (exitTs < startOfWeekTs) weeklyStartBal = rollingBalance + pnl;
      if (exitTs < startOfMonthTs) monthlyStartBal = rollingBalance + pnl;

      rollingBalance = Math.max(1, rollingBalance + pnl);

      currentPnL += pnl;
      if (currentPnL > maxPnL) maxPnL = currentPnL;
      const dd = maxPnL - currentPnL;
      if (dd > maxDD) maxDD = dd;
      const peakBalance = effectiveStartingBalance + maxPnL;
      const ddPct = peakBalance > 0 ? (dd / peakBalance) * 100 : 0;
      if (ddPct > maxDDPct) maxDDPct = ddPct;

      cumulativePnL[i] = { ts: t.exit_ts!.toISOString(), pnl: roundTo(currentPnL, 2) };

      if (exitTs >= startOfDayTs) dailyPnL += pnl;
      if (exitTs >= startOfWeekTs) weeklyPnL += pnl;
      if (exitTs >= startOfMonthTs) monthlyPnL += pnl;

      const dayTs = Math.floor(exitTs / 86400000) * 86400000;
      if (!dailyBuckets.has(dayTs)) dailyBuckets.set(dayTs, { pnl: 0, startBal: tradeStartBal });
      dailyBuckets.get(dayTs)!.pnl += pnl;

      const tDay = new Date(exitTs).getUTCDay();
      const tDiff = tDay === 0 ? 6 : tDay - 1;
      const weekTs = dayTs - (tDiff * 86400000);
      if (!weeklyBuckets.has(weekTs)) weeklyBuckets.set(weekTs, { pnl: 0, startBal: tradeStartBal });
      weeklyBuckets.get(weekTs)!.pnl += pnl;

      const hour = t.exit_ts!.getUTCHours();
      const stats = todStats[hour];
      stats.pnl += pnl;
      stats.total += 1;
      sumReturnPct += tradeReturnPct;
      sumSquaredReturnPct += tradeReturnPct * tradeReturnPct;

      if (pnl > 0) {
        stats.wins += 1;
        totalWins += 1;
        grossProfit += pnl;
        grossProfitPct += tradeReturnPct;
      } else if (pnl < 0) {
        totalLosses += 1;
        grossLoss += Math.abs(pnl);
        grossLossPct += Math.abs(tradeReturnPct);
        downsideSumSquaredReturnPct += tradeReturnPct * tradeReturnPct;
      }
    }

    const dailyHistory = Array.from(dailyBuckets.keys())
      .sort((a, b) => a - b)
      .slice(-7)
      .map(ts => {
        const b = dailyBuckets.get(ts)!;
        return {
          label: new Date(ts).toISOString().split('T')[0],
          pnl: roundTo(b.pnl, 2),
          pnlPct: roundTo((b.pnl / Math.max(1, b.startBal)) * 100, 2)
        };
      });

    const weeklyHistory = Array.from(weeklyBuckets.keys())
      .sort((a, b) => a - b)
      .slice(-4)
      .map(ts => {
        const b = weeklyBuckets.get(ts)!;
        return {
          label: `Week of ${new Date(ts).toISOString().split('T')[0]}`,
          pnl: roundTo(b.pnl, 2),
          pnlPct: roundTo((b.pnl / Math.max(1, b.startBal)) * 100, 2)
        };
      });

    const timeOfDay = todStats.map((stats, hour) => ({
      hour, ...stats, winRate: stats.total > 0 ? (stats.wins / stats.total) * 100 : 0,
    }));

    const avgWin = totalWins > 0 ? grossProfit / totalWins : 0;
    const avgLoss = totalLosses > 0 ? grossLoss / totalLosses : 0;
    const avgWinPct = totalWins > 0 ? grossProfitPct / totalWins : 0;
    const avgLossPct = totalLosses > 0 ? grossLossPct / totalLosses : 0;
    const expectancyPct = totalTrades > 0 ? sumReturnPct / totalTrades : 0;
    const avgWinLossRatio = avgLoss > 0 ? avgWin / avgLoss : 0;
    const profitFactor = grossLoss > 0 ? grossProfit / grossLoss : (grossProfit > 0 ? 100 : 0);
    const overallPnlPct = effectiveStartingBalance > 0 ? (currentPnL / effectiveStartingBalance) * 100 : 0;

    let sharpeRatio = 0;
    let sortinoRatio = 0;
    if (totalTrades > 1) {
      const meanReturn = sumReturnPct / totalTrades;
      const variance = Math.max(0, (sumSquaredReturnPct / totalTrades) - (meanReturn * meanReturn));
      const stdDev = Math.sqrt(variance);
      const downsideVariance = downsideSumSquaredReturnPct / totalTrades;
      const downsideStdDev = Math.sqrt(downsideVariance);
      if (stdDev > 0) sharpeRatio = meanReturn / stdDev;
      if (downsideStdDev > 0) sortinoRatio = meanReturn / downsideStdDev;
    }

    return {
      cumulativePnL, maxDrawdown: roundTo(maxDD, 2), maxDrawdownPct: roundTo(maxDDPct, 2), timeOfDay, totalTrades,
      overallWinRate: totalTrades > 0 ? (totalWins / totalTrades) * 100 : 0,
      overallPnlPct: roundTo(overallPnlPct, 2), avgWin: roundTo(avgWin, 2), avgLoss: roundTo(avgLoss, 2),
      avgWinPct: roundTo(avgWinPct, 2), avgLossPct: roundTo(avgLossPct, 2),
      expectancyPct: roundTo(expectancyPct, 2), avgWinLossRatio: roundTo(avgWinLossRatio, 2),
      profitFactor: roundTo(profitFactor, 2), sharpeRatio: roundTo(sharpeRatio, 2), sortinoRatio: roundTo(sortinoRatio, 2),
      periodic: {
        daily: { pnl: roundTo(dailyPnL, 2), pnlPct: roundTo((dailyPnL / Math.max(1, dailyStartBal)) * 100, 2) },
        weekly: { pnl: roundTo(weeklyPnL, 2), pnlPct: roundTo((weeklyPnL / Math.max(1, weeklyStartBal)) * 100, 2) },
        monthly: { pnl: roundTo(monthlyPnL, 2), pnlPct: roundTo((monthlyPnL / Math.max(1, monthlyStartBal)) * 100, 2) },
      },
      periodicHistory: { daily: dailyHistory, weekly: weeklyHistory }
    };
  }
}
