export const CONFIG_LIMITS = {
  WATCHLIST_MIN: 1,
  WATCHLIST_MAX: 200,
  WATCHLIST_DEFAULT: 25,
  WATCHLIST_OFFSET_MIN: 0,
  WATCHLIST_OFFSET_MAX: 100,
  WATCHLIST_OFFSET_DEFAULT: 0,

  SL_DISTANCE_MIN: 0.1,
  SL_DISTANCE_MAX: 10.0,
  SL_DISTANCE_DEFAULT: 0.8,

  RISK_PER_TRADE_MIN: 0.01,
  RISK_PER_TRADE_MAX: 100.0,
  RISK_PER_TRADE_DEFAULT: 1.0,

  MAX_TOTAL_RISK_MIN: 0.1,
  MAX_TOTAL_RISK_MAX: 100.0,
  MAX_TOTAL_RISK_DEFAULT: 5.0,

  HOT_LOOP_MIN: 500,
  HOT_LOOP_DEFAULT: 5000,
  MAIN_LOOP_MIN: 1000,
  MAIN_LOOP_DEFAULT: 15000,

  MAX_VARIANTS: 10,
  MAX_SINGLE_SYMBOL_MONITORS: 100,
  MAX_TRADING_WINDOWS: 10,
  MAX_SIGNALS: 20,

  SCAN_PCT_THRESHOLD_MIN: 0.0,
  MAX_OPEN_TRADES_MIN: 1,
  MAX_OPEN_TRADES_DEFAULT: 5,
  TP_RATIO_MIN: 0.1,
  TP_RATIO_DEFAULT: 2.0,
  TOTAL_SL_GUARD_DEFAULT: 200.0,
  PAPER_STARTING_BALANCE_DEFAULT: 10000.0,
  LIVE_STARTING_BALANCE_DEFAULT: 10000.0,
  LEVERAGE_MIN: 1,
  LEVERAGE_MAX: 125,
  LEVERAGE_DEFAULT: 1,
  SLIPPAGE_THRESHOLD_DEFAULT: 0.001,
};

export const ENGINE_CONSTANTS = {
  BINANCE_RATE_LIMIT_DEFAULT: 2400,
};
